"""
Download AoPS wiki pages and write them into the pipeline cache format.

Usage:
    python pipeline/download-cache.py

Run from the repo root. Reads fetch-urls.txt (generated by this repo) and writes
each page's raw wikitext to pipeline/.cache/<path>.json in the format that
pipeline/src/wiki.ts expects:

    { "page": "<title>", "wikitext": "<raw content or null>", "fetchedAt": "<ISO>" }

A null wikitext means the page does not exist (404) — the pipeline treats that as a
confirmed miss and will not re-probe it.

Already-cached files are skipped, so the script is safe to resume after interruption.

Rate limiting: each request waits a random delay in [MIN_DELAY_S, MAX_DELAY_S].
The jitter is important — a perfectly regular interval is easier for bot-detection
to fingerprint than human-like variation. If you hit 429s, increase both values.
"""

import json
import os
import random
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

MIN_DELAY_S = 2.0
MAX_DELAY_S = 5.0
CACHE_DIR = os.path.join("pipeline", ".cache")
URLS_FILE = "fetch-urls.txt"
USER_AGENT = "amc-diagnostic-tagger/1.0 (topic metadata extraction; contact repo owner)"


def fetch(url: str) -> str | None:
    """Return page body, or None on 404. Raises on other errors."""
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def main() -> None:
    if not os.path.exists(URLS_FILE):
        print(f"ERROR: {URLS_FILE} not found. Run this from the repo root.", file=sys.stderr)
        sys.exit(1)

    with open(URLS_FILE) as f:
        rows = [line.strip().split("\t") for line in f if line.strip()]

    total = len(rows)
    done = skipped = errors = 0

    for i, (url, cache_file) in enumerate(rows, 1):
        path = os.path.join(CACHE_DIR, cache_file)

        if os.path.exists(path):
            skipped += 1
            continue

        # Decode the page title from the URL for the cache entry
        qs = urllib.parse.parse_qs(urllib.parse.urlparse(url).query)
        page = urllib.parse.unquote(qs.get("title", [""])[0])

        try:
            wikitext = fetch(url)
        except Exception as e:
            print(f"  [{i}/{total}] ERROR {page}: {e}", file=sys.stderr)
            errors += 1
            time.sleep(random.uniform(MIN_DELAY_S, MAX_DELAY_S))
            continue

        os.makedirs(os.path.dirname(path), exist_ok=True)
        entry = {
            "page": page,
            "wikitext": wikitext,
            "fetchedAt": datetime.now(timezone.utc).isoformat(),
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(entry, f, indent=2, ensure_ascii=False)

        status = "missing" if wikitext is None else f"{len(wikitext)} chars"
        delay = random.uniform(MIN_DELAY_S, MAX_DELAY_S)
        print(f"  [{i}/{total}] {page} — {status} (next in {delay:.1f}s)")
        done += 1
        time.sleep(delay)

    print(f"\ndone: {done} fetched, {skipped} already cached, {errors} errors")


if __name__ == "__main__":
    main()
