import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CACHE_DIR } from "./wiki.js";

const OUT_PATH = join(process.cwd(), "src", "lib", "statement-cache.generated.ts");

interface CacheEntry {
  page: string;
  wikitext: string | null;
}

/**
 * Stage 3.5 (deploy prep). Merges every wiki-fetch cache file under pipeline/.cache/
 * into one lookup object, keyed by page, and writes it as TypeScript SOURCE (an
 * exported object literal), not a JSON file read at runtime.
 *
 * Both a per-file cache (thousands of small entries) and a single merged bundle.json
 * read via readFile() were silently missing from the deployed Vercel function at
 * runtime (ENOENT), despite a clean next build trace manifest and reasonable upload
 * size — and a static `import bundle from "./bundle.json"` didn't help either, since
 * Next still compiles a JSON import for a Node target to a runtime file read, not an
 * inlined literal. Emitting actual .ts source is the only form guaranteed to become
 * part of the compiled JS with no separate file-tracing/packaging step involved.
 *
 * Run after `npm run fetch` and before deploying with SHOW_PROBLEM_STATEMENTS=1.
 * Does not touch pipeline/.cache/classify/ (LLM tagging cache, unrelated to
 * statement display) or _last-failure.html (fetch debug dump).
 */
async function walk(dir: string, bundle: Record<string, string | null>): Promise<void> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "classify") continue;
      await walk(full, bundle);
    } else if (entry.name.endsWith(".json") && entry.name !== "bundle.json") {
      try {
        const data = JSON.parse(await readFile(full, "utf8")) as CacheEntry;
        if (typeof data.page === "string") bundle[data.page] = data.wikitext;
      } catch {
        console.warn(`  skipping unreadable cache file: ${full}`);
      }
    }
  }
}

async function main(): Promise<void> {
  const bundle: Record<string, string | null> = {};
  await walk(CACHE_DIR, bundle);
  const source =
    "// Generated by `npm run bundle-cache` — do not edit by hand.\n" +
    "const bundle: Record<string, string | null> = " +
    JSON.stringify(bundle) +
    ";\nexport default bundle;\n";
  await writeFile(OUT_PATH, source);
  console.log(`bundled ${Object.keys(bundle).length} pages -> ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
